title: Yubo Yang's Homepage
page-top-title: Yubo Yang
top-section-bg-text: Computer Science
home-subtitle: Yubo Yang &ensp;|&ensp;杨宇博
copyright-text: '&copy; Yubo Yang 2019-2025. All Rights Reserved.'
